# Generated by Django 6.1.1 on 2026-09-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('zone_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('zone_name', models.CharField(max_length=200)),
                ('balance_rupees', models.FloatField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'billing_wallet',
            },
        ),
        migrations.CreateModel(
            name='BillingDailyRollup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.CharField(max_length=64)),
                ('zone_name', models.CharField(max_length=200)),
                ('simulated_day', models.BigIntegerField()),
                ('total_kwh', models.FloatField()),
                ('total_overage_kwh', models.FloatField()),
                ('avg_rate_per_kwh', models.FloatField()),
                ('total_cost_rupees', models.FloatField()),
                ('total_overage_cost_rupees', models.FloatField()),
                ('sample_count', models.IntegerField()),
                ('first_tick', models.BigIntegerField()),
                ('last_tick', models.BigIntegerField()),
            ],
            options={
                'db_table': 'billing_billing_daily_rollup',
                'ordering': ['-simulated_day'],
                'indexes': [models.Index(fields=['simulated_day'], name='ix_billing_daily_rollup_day')],
                'constraints': [models.UniqueConstraint(fields=('zone_id', 'simulated_day'), name='uq_billing_daily_rollup_zone_day')],
            },
        ),
        migrations.CreateModel(
            name='BillingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.CharField(max_length=64)),
                ('zone_name', models.CharField(max_length=200)),
                ('tick_number', models.BigIntegerField()),
                ('kwh', models.FloatField()),
                ('overage_kwh', models.FloatField()),
                ('rate_per_kwh', models.FloatField()),
                ('cost_rupees', models.FloatField()),
                ('overage_cost_rupees', models.FloatField()),
                ('recorded_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'billing_billing_record',
                'ordering': ['-tick_number'],
                'indexes': [models.Index(fields=['zone_id', 'recorded_at'], name='ix_billing_record_zone_time')],
                'constraints': [models.UniqueConstraint(fields=('zone_id', 'tick_number'), name='uq_billing_record_zone_tick')],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.CharField(max_length=64)),
                ('type', models.CharField(choices=[('BILL_DEBIT', 'BILL_DEBIT'), ('PLANT_PURCHASE', 'PLANT_PURCHASE'), ('PLANT_UPGRADE', 'PLANT_UPGRADE'), ('PLANT_MAINTENANCE', 'PLANT_MAINTENANCE'), ('PLANT_DECOMMISSION', 'PLANT_DECOMMISSION'), ('STORAGE_PURCHASE', 'STORAGE_PURCHASE'), ('BILL_REVENUE', 'BILL_REVENUE')], max_length=32)),
                ('amount_rupees', models.FloatField()),
                ('balance_after_rupees', models.FloatField()),
                ('occurred_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'billing_wallet_transaction',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['zone_id', 'occurred_at'], name='ix_wallet_txn_zone_time')],
            },
        ),
    ]
