# Generated by Django 6.1.1 on 2026-09-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneCapacity',
            fields=[
                ('zone_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('zone_name', models.CharField(max_length=200)),
                ('capacity_kw', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'distributor_zone_capacity',
            },
        ),
        migrations.CreateModel(
            name='DistributionDailyRollup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.CharField(max_length=64)),
                ('zone_name', models.CharField(max_length=200)),
                ('simulated_day', models.BigIntegerField()),
                ('avg_demand_kw', models.FloatField()),
                ('min_demand_kw', models.FloatField()),
                ('max_demand_kw', models.FloatField()),
                ('avg_supplied_kw', models.FloatField()),
                ('min_supplied_kw', models.FloatField()),
                ('max_supplied_kw', models.FloatField()),
                ('avg_balance_kw', models.FloatField()),
                ('min_balance_kw', models.FloatField()),
                ('max_balance_kw', models.FloatField()),
                ('sample_count', models.IntegerField()),
                ('first_tick', models.BigIntegerField()),
                ('last_tick', models.BigIntegerField()),
            ],
            options={
                'db_table': 'distributor_distribution_daily_rollup',
                'ordering': ['-simulated_day'],
                'indexes': [models.Index(fields=['simulated_day'], name='ix_dist_daily_rollup_day')],
                'constraints': [models.UniqueConstraint(fields=('zone_id', 'simulated_day'), name='uq_dist_daily_rollup_zone_day')],
            },
        ),
        migrations.CreateModel(
            name='DistributionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.CharField(max_length=64)),
                ('zone_name', models.CharField(max_length=200)),
                ('tick_number', models.BigIntegerField()),
                ('demand_kw', models.FloatField()),
                ('supplied_kw', models.FloatField()),
                ('balance_kw', models.FloatField()),
                ('recorded_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'distributor_distribution_record',
                'ordering': ['-tick_number'],
                'indexes': [models.Index(fields=['zone_id', 'recorded_at'], name='ix_dist_record_zone_time'), models.Index(fields=['recorded_at'], name='ix_dist_record_time')],
            },
        ),
    ]
