# Generated by Django 6.1.1 on 2026-09-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PowerPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('THERMAL', 'Thermal'), ('SOLAR', 'Solar'), ('WIND', 'Wind')], max_length=20)),
                ('capacity_mw', models.FloatField()),
                ('min_output_mw', models.FloatField()),
                ('base_output_mw', models.FloatField()),
                ('current_output_mw', models.FloatField(default=0.0)),
                ('energy_mwh', models.FloatField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'producer_power_plant',
            },
        ),
        migrations.CreateModel(
            name='GenerationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.BigIntegerField()),
                ('plant_type', models.CharField(choices=[('THERMAL', 'Thermal'), ('SOLAR', 'Solar'), ('WIND', 'Wind')], max_length=20)),
                ('tick_number', models.BigIntegerField()),
                ('output_mw', models.FloatField()),
                ('frequency_deviation', models.FloatField()),
                ('recorded_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'producer_generation_record',
                'ordering': ['-tick_number'],
                'indexes': [models.Index(fields=['plant_id', 'recorded_at'], name='ix_gen_record_plant_time'), models.Index(fields=['recorded_at'], name='ix_gen_record_time')],
            },
        ),
    ]
