# Generated by Django 6.1.1 on 2026-09-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationRollup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.BigIntegerField()),
                ('plant_type', models.CharField(choices=[('THERMAL', 'Thermal'), ('SOLAR', 'Solar'), ('WIND', 'Wind')], max_length=20)),
                ('bucket_start', models.DateTimeField()),
                ('avg_output_mw', models.FloatField()),
                ('min_output_mw', models.FloatField()),
                ('max_output_mw', models.FloatField()),
                ('energy_mwh', models.FloatField()),
                ('sample_count', models.IntegerField()),
                ('first_tick', models.BigIntegerField()),
                ('last_tick', models.BigIntegerField()),
            ],
            options={
                'db_table': 'producer_generation_rollup',
                'ordering': ['-bucket_start'],
                'indexes': [models.Index(fields=['bucket_start'], name='ix_generation_rollup_bucket')],
                'constraints': [models.UniqueConstraint(fields=('plant_id', 'bucket_start'), name='uq_generation_rollup_plant_bucket')],
            },
        ),
    ]
