# Generated by Django 6.1.1 on 2026-09-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_tick', models.BigIntegerField(default=0)),
                ('frequency_deviation_hz', models.FloatField(default=0.0)),
                ('auto_control', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Simulation state',
                'verbose_name_plural': 'Simulation state',
            },
        ),
    ]
